# Imagen base pequeña y rápida para servir contenido estático
FROM nginx:alpine

# Elimina archivos HTML por defecto de Nginx
RUN rm -rf /usr/share/nginx/html/*
# Copia tu build Angular ya generado
COPY dist/ /usr/share/nginx/html/

# Expone el puerto 80
EXPOSE 4200
# Comando por defecto
CMD ["nginx", "-g", "daemon off;"]
