name: Build Frontend

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 20 with npm Cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Setup Java 17 with Gradle Cache
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Generate typescript types
        run: ./gradlew generateTypes

      - name: Install dependencies to Production
        working-directory: frontend
        run: npm ci --production --no-fund --no-audit --legacy-peer-deps

      - name: Build frontend
        working-directory: frontend
        run: npm run build
