# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy

on:
  push:
    branches:
      - deploy
    paths:
      - ".github/workflows/cloud-deploy.yml"
      - ".github/workflows/build-backend.yml"
      - ".github/workflows/build-frontend.yml"
      - ".github/workflows/build-dependencies.yml"

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-backend:
    uses: ./.github/workflows/build-backend.yml

  build-frontend:
    uses: ./.github/workflows/build-frontend.yml

  build-dependencies:
    uses: ./.github/workflows/build-dependencies.yml

  deploy-dependencies:
    runs-on: ubuntu-latest
    environment: google-vps
    needs: build-dependencies

    steps:
      - name: Restore datastore image tar
        uses: actions/cache@v4
        with:
          path: datastore-image.tar
          key: datastore-${{ github.sha }}

      - name: Restore solr image tar
        uses: actions/cache@v4
        with:
          path: solr-image.tar
          key: solr-${{ github.sha }}

      - name: Connect to VPS with SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.VPS_KEY }}" > ~/.ssh/private
          chmod 600 ~/.ssh/private
          ssh -i ~/.ssh/private -o "StrictHostKeyChecking no" "${{secrets.VPS_USER}}"@$"${{secrets.VPS_HOST}}"
      - run: exit

  deploy-backend:
    runs-on: ubuntu-latest
    environment: google-vps
    needs: [build-backend, deploy-dependencies]

    steps:
      - name: Restore backend image tar
        uses: actions/cache@v4
        with:
          path: backend-image.tar
          key: backend-${{ github.sha }}

      - name: Connect to VPS with SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.VPS_KEY }}" > ~/.ssh/private
          chmod 600 ~/.ssh/private
          ssh -i ~/.ssh/private -o "StrictHostKeyChecking no" "${{secrets.VPS_USER}}"@$"${{secrets.VPS_HOST}}"
      - run: exit

  deploy-frontend:
    runs-on: ubuntu-latest
    environment: google-vps
    needs: [build-frontend]

    steps:
      - name: Restore frontend image tar
        uses: actions/cache@v4
        with:
          path: frontend-image.tar
          key: frontend-${{ github.sha }}

      - name: Deploy frontend on VPS via SSH
        env:
          VPS_KEY: ${{ secrets.VPS_KEY }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
        run: |
          # Create the .ssh directory if it doesn't exist and set the private key from the secret
          mkdir -p ~/.ssh/
          echo "$VPS_KEY" > ~/.ssh/private
          chmod 600 ~/.ssh/private

          # Copy the frontend image tar to the VPS
          scp -i ~/.ssh/private -o "StrictHostKeyChecking no" frontend-image.tar $VPS_USER@$VPS_HOST:~/frontend-image.tar

          # Connect to the VPS using SSH and execute the deployment script
          ssh -i ~/.ssh/private -o "StrictHostKeyChecking no" $VPS_USER@$VPS_HOST << 'ENDSSH'

            # Delete the old container if it exists
            CONTAINER_ID=$(sudo docker ps -q --filter "publish=4200")
            if [ ! -z "$CONTAINER_ID" ]; then
              sudo docker stop $CONTAINER_ID
              sudo docker rm $CONTAINER_ID
            fi

            # Delete the old image if it exists
            IMAGE_ID=$(sudo docker images -q frontend:latest)
            if [ ! -z "$IMAGE_ID" ]; then
              sudo docker rmi -f $IMAGE_ID
            fi

            # Load the new frontend image and run it
            sudo docker load -i ~/frontend-image.tar
            sudo docker run -d -p 4200:4200 --name frontend frontend:latest
          ENDSSH
      - run: exit
